model:
  type: "bert"
  name: "bert-base-cased"
  hf_checkpoint: "neuralmind/bert-base-portuguese-cased"
  hidden_dropout_prob: 0.1
  attention_dropout_prob: 0.1

data:
  name: "lener"
  max_seq_length: 512
  batch_size: 16
  select: -1
  collator:
    name: "SplitInstanceCollate"
    overlap: 128

training:
  num_epochs: 3
  learning_rate: 2.0e-4
  warmup_steps: 500
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  criterion:
    name: "CrossEntropyLoss"
  optimizer:
    type: "adamw"
  scheduler: "linear"

output:
  results_dir: "../outputs/"